[package]
name = "personal-server-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
axum-server = "0.8.0"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.37"
serde_json = "1"
