services:
  monitor:
    container_name: personal-server-monitor
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8010"
    networks:
      - webpage_network

networks:
  webpage_network:
    external: True